name: clerk
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.3
  animated_text_kit: ^4.2.1
  flutter_screenutil: ^5.3.1
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  google_sign_in: ^6.0.2
  motion_tab_bar_v2: ^0.2.5
  steps_indicator: ^1.3.0
  cloud_firestore: ^4.1.0
  cupertino_tabbar: ^2.0.0
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  firebase_storage: ^11.0.6
  dartz: ^0.10.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  country_code_picker: ^3.0.0
  freezed_annotation: ^2.2.0
  logger: ^1.1.0
  pin_code_fields: ^7.4.0
  file_picker: ^5.2.5
  cloud_functions: ^4.0.7
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.11
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^3.0.0
  loader_overlay: ^2.3.2
  form_validator: ^2.1.1
  email_validator: ^2.1.17
  shimmer: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.12.0



flutter:
  assets:
    - assets/images/
    - assets/illustrations/




  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/clerk_launcher_icon.jpg"