// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZKyW4MglPKhqLeLwSORz8kstfgv6CjQ0',
    appId: '1:430019546238:android:7dfc7959efb062bbf35c2f',
    messagingSenderId: '430019546238',
    projectId: 'clerk-fbcaf',
    storageBucket: 'clerk-fbcaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDteH8yL_R5C6-W8vlZ7p_8tpduHQAUJDM',
    appId: '1:430019546238:ios:02fefed76e7b6c24f35c2f',
    messagingSenderId: '430019546238',
    projectId: 'clerk-fbcaf',
    storageBucket: 'clerk-fbcaf.appspot.com',
    androidClientId: '430019546238-a3s0ko75je2ta7dor5s7o6f03ov2rbb6.apps.googleusercontent.com',
    iosClientId: '430019546238-5tdmbu9ot0dj4pb8inoa7t32eml58ehh.apps.googleusercontent.com',
    iosBundleId: 'com.modcons.clerk',
  );
}
